# Generated by Django 5.1.5 on 2025-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='onclick_func',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
