# Generated by Django 5.1.5 on 2025-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_items_onclick_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='icon',
            field=models.ImageField(upload_to='media'),
        ),
    ]
