# Generated by Django 5.1.5 on 2025-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0003_alter_items_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='icon',
            field=models.FileField(upload_to='media'),
        ),
    ]
