# Generated by Django 5.1.5 on 2025-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
